name: allskills
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^2.3.0
  google_sign_in: ^5.0.0
  weather:
  weather_icons: 3.0.0
  flutter_countdown_timer: ^4.1.0
  video_player:
  percent_indicator: 3.3.0-nullsafety.1
  camera:
  data_table_2: ^2.0.4
  #open_weather_client: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/logo_medium.png
    - assets/images/logo_small.png
    - assets/images/background.png
    - assets/images/the_player_icon.png
    - assets/images/the_gm_icon.png
    - assets/images/the_scout_icon.png
    - assets/images/small_IG_icon.png
    - assets/images/small_YT_icon.png
    - assets/images/small_FB_icon.png
    - assets/images/small_TT_icon.png
    - assets/images/profile_picture.png
    - assets/images/appbar_bg.png
    - assets/images/video_thumbnail.jpg
    - assets/images/match_photo_1.jpg
    - assets/images/match_photo_2.jpg
    - assets/images/nick_suzuki.jpg
    - assets/images/logo_small_white.png
    - assets/images/logo_small_purple.png
    - assets/videos/Video_1.mp4
    - assets/videos/Video_2.mp4
    - assets/images/frank.jpg
  #   - images/textured-background.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Asphaltic
       fonts:
         - asset: assets/fonts/Asphaltic-Scratch.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
